# This is a basic workflow to help you get started with Actions

name: Build native image for linux arm64

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - run: |
        docker run --rm --privileged multiarch/qemu-user-static:register --reset

    - uses: docker://oracle/graalvm-ce:20.1.0-java8@sha256:21d0cb01226f6b9f1ded61ce694f31c489ed0a81d11e4f599025739ea37e33f3
      name: Debug
      with:
        args: 'uname -a'
