# This is a basic workflow to help you get started with Actions

name: Build native image for linux arm64

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - run: |
        docker run --rm --privileged multiarch/qemu-user-static:register --reset


    - uses: docker://oracle/graalvm-ce:20.1.0-java8@sha256:21d0cb01226f6b9f1ded61ce694f31c489ed0a81d11e4f599025739ea37e33f3
      name: Install maven
      with:
        args: >
          mkdir -p /usr/share/maven /usr/share/maven/ref \
          && curl -fsSL -o /tmp/apache-maven.tar.gz https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz \
          && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
          && rm -f /tmp/apache-maven.tar.gz \
          && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

    - uses: docker://oracle/graalvm-ce:20.1.0-java8@sha256:21d0cb01226f6b9f1ded61ce694f31c489ed0a81d11e4f599025739ea37e33f3
      name: Setup env
      with:
        args: fc-cache -f -v && gu install native-image

    - uses: docker://oracle/graalvm-ce:20.1.0-java8@sha256:21d0cb01226f6b9f1ded61ce694f31c489ed0a81d11e4f599025739ea37e33f3
      name: Run build
      with:
        args: mvn package
               
    - uses: actions/upload-artifact@v2
      with:
        name: simple-native
        path: target/simple-native
